### ISSUE TITLE
forward TSDocs on transpiling

### ISSUE THREAD

**Issue by ibuki2003** [aspida/aspida#531]
## Description

forward TSDocs from `Methods` into `$api.ts`

### example
input(`foo/bar/index.ts`)
```ts
/**
 * route summary
 */
interface Methods {
  /**
   * method summary
   */
  get: {
    //
  };
}
```

output
```ts
declare const api: <T>({ baseURL, fetch }: AspidaClient<T>) => {
  foo: {
    /**
	 * route summary
	 */
    bar: {
	  /**
	   * method summary
	   */
      get: (/* */)
    }
  }
};
```

**Comment by solufa** [comment]
Thanks for posting this.
I could figure out what to do.

**Comment by solufa** [comment]
@ibuki2003 

TSDoc support was added in aspida@v0.21.0!
See: https://github.com/aspida/aspida/tree/master/packages/aspida/docs/ja#tips10

Thank you for your contribution.
