### ISSUE TITLE
OpenAPIファイル(swagger)からクライアント作成時にすべてoptionalになってしまう

### ISSUE THREAD

**Issue by redshoga** [aspida/aspida#553]
## Description

タイトル通りです。
Swagger上で`required: true`な項目も型すべてoptional(例: `hoge?: string`)に変換されます。

```
$ npx openapi2aspida -i https://petstore.swagger.io/v2/swagger.json
# api/$api.ts was built successfully.
```

## Describe the solution you'd like

swaggerファイルで定義したrequiredが型に反映される。

## Additional context

swaggerファイルを更新した際に、型チェックでミスに気づかない場合があるので解決したいと考えています。
別途解決策などあればご教授お願いします。

**Comment by solufa** [comment]
@redshoga 

投稿ありがとうございます
https://petstore.swagger.io/v2/swagger.json
のどの`required: true`が反映されていないか教えていただけますか？
他のSwaggerファイルでもいいです

perstoreだとqueryのrequired指定が多くてプロパティ自体にrequiredがあるエンドポイントがパッとは見つからず・・・

**Comment by solufa** [comment]
Issueに全く関係ないですが、openapi2aspidaは周辺ツールで最も作るのが大変だったので使ってくれている人がいて嬉しいです

**Comment by redshoga** [comment]
申し訳ないです!勘違いでした。
以下のように正常に動きました。
https://github.com/redshoga/openapi2aspida-optional-test

> Issueに全く関係ないですが、openapi2aspidaは周辺ツールで最も作るのが大変だったので使ってくれている人がいて嬉しいです
かなり助かっています! ありがとうございます。

以下も試したのですが、エラーがJavaになってしまう/生成ファイルが扱いにくいなどあって`openapi2aspida`に助けられています。

https://github.com/OpenAPITools/openapi-generator

