### ISSUE TITLE
Conditional resBody based on reqBody

### ISSUE THREAD

**Issue by jakeklassen** [aspida/aspida#554]
## Description

Great library :+1: 

I'm looking for a way to conditionally define the response body based on the request body. As an example:

`POST /api/users body: { email: 'email' } -> User`

`POST /api/users body: [{ email: 'email_one' }, { email: 'email_two' }] -> Array<User>`

Basically RESTful endpoints that support the notion of `multi: true` (feathersjs as an example).

## Describe the solution you'd like

Maybe something where positional arguments are matched:

```typescript
type User = {
  email: string;
};

export type Methods = {
  post: {
    reqBody: [Partial<User>, Array<Partial<User>>],
    resBody: [User, Array<User>],
  }
}
``` 

Or the HTTP method properties could be functions that evaluate to a conditional type based on a `reqBody` param?

I haven't dug into the library implementation at all yet so just spit balling here. 

## Describe alternatives you've considered

For this immediate use case just ignoring the ability to create a `User` asset individually and just use an array based approach at all times.

## Additional context

None

**Comment by solufa** [comment]
@jakeklassen 

Thanks for posting.
I'll see if this is possible with function overloading.

**Comment by solufa** [comment]
@jakeklassen 

I added polymorphic request.
Does this solve the problem?

https://github.com/aspida/aspida#tips6

**Comment by jakeklassen** [comment]
@solufa 

This looks good so far. Cheers :beers:

**Comment by FarhanShares** [comment]
I had an issue which I've came with a solution, leaving it here, hopefully someone might find it helpful.

Interface:
```typescript
 get: {
    polymorph: [
      {
        query: {
          map: boolean
        }

        resBody: IPermissionMapList
      },
      {
        query: {
          limit?: number
          page?: number
        }

        resBody: IPermissionList
      }
    ]
  }

```

Build:
```typescript
get: (() => {
            function getRequest(option: { query: Methods0['get']['polymorph'][0]['query'], config?: T }): Promise<AspidaResponse<Methods0['get']['polymorph'][0]['resBody']>>
            function getRequest(option?: { query?: Methods0['get']['polymorph'][1]['query'], config?: T }): Promise<AspidaResponse<Methods0['get']['polymorph'][1]['resBody']>>
            function getRequest(option: any) {
              return fetch(prefix, PATH0, GET, option).send()
            }
            return getRequest
          })(),
          $get: (() => {
            function $getRequest(option: { query: Methods0['get']['polymorph'][0]['query'], config?: T }): Promise<Methods0['get']['polymorph'][0]['resBody']>
            function $getRequest(option?: { query?: Methods0['get']['polymorph'][1]['query'], config?: T }): Promise<Methods0['get']['polymorph'][1]['resBody']>
            function $getRequest(option: any) {
              return fetch(prefix, PATH0, GET, option).send().then(r => r.body)
            }
            return $getRequest
          })(),

```

Error:

```
This overload signature is not compatible with its implementation signature.ts(2394)
$api.ts(53, 22): The implementation signature is declared here.
```

Observation:
I must define reqBody to actually make it clear which resBody should be used & it fulfills the implementation signature of aspida. So, this makes it a required thing. 

Solution: 
Added reqBody for the get request along with the rest of the codes, it works nicely .
```ts 
 reqBody: {
    map: true
}
```
