### ISSUE TITLE
[Docs] How to use aspida with some Frameworks (such as Next.js) which is build-in fetch API globally

### ISSUE THREAD

**Issue by matamatanot** [aspida/aspida#598]
## Description
Frameworks such as Next.js may introduce polyfill in build-in for the server-side Fetch (like) API.

https://github.com/vercel/next.js/pull/12353

> This adds a similar polyfilling behavior to the Node.js side of things to ensure fetch can be used without any imports needed.
> Previously users would need to import isomorphic-fetch or isomorphic-unfetch, this won't be needed once this has landed.

In such a case, should I use only @aspida/fetch instead of @aspida/node-fetch?

## Describe the solution you'd like

Add Docs.

## Describe alternatives you've considered

Always you should use @aspida/node-fetch.

**Comment by solufa** [comment]
@matamatanot 

You can also use @aspida/fetch to do SSR in Next.js.
This code is used by [create-frourio-app](https://github.com/frouriojs/create-frourio-app).

```ts
import aspida from '@aspida/fetch'
import api from '../api/$api'

export const apiClient = api(aspida())
```
