### ISSUE TITLE
[@aspida/swr] Auth token expiration pattern witch Conditional Fetching

### ISSUE THREAD

**Issue by matamatanot** [aspida/aspida#599]
## Description
`swr` has a Conditional Fetching feature.
https://swr.vercel.app/docs/conditional-fetching#conditional

When using a combination of `Firebase.auth` and `swr`, I sometimes take advantage of Conditional Fetching and write the following.
https://github.com/vercel/swr/discussions/684#discussioncomment-94198

Do such workarounds exist?
Looking at the code it seems like it would be difficult to take advantage of Conditional Fetching.

## Describe the solution you'd like

Use `@aspida/swr` with auth token expiration pattern witch Conditional Fetching.

## Describe alternatives you've considered

Fork @aspida/swr and extend arguments for my case.

**Comment by solufa** [comment]
@matamatanot 

Please update and use `enabled = false` option like `React Query`.
https://github.com/aspida/aspida/tree/master/packages/aspida-swr#conditional-fetching

**Comment by matamatanot** [comment]
@solufa 
Thanks!
