### ISSUE TITLE
Decode endpoints that contain special characters for JavaScript Primitive String

### ISSUE THREAD

**Issue by matamatanot** [aspida/aspida#603]
## Description
Our some API endpoints are
`/v1/users:register`

In Docs,
`// req -> GET: /foo%3Abar (= /foo:bar)`
but the server doesn't resolve this in our case.
Is it possible to set the decoding as a cli option?

**$api.ts**
``` 
const api = <T>({ baseURL, fetch }: AspidaClient<T>) => {
  const prefix = (baseURL === undefined ? "" : baseURL).replace(/\/$/, "");
  const PATH0 = "/v1/users";
  const PATH1 = "/v1/users/profile:uploadImage"; // before `profile%3AuploadImage`
  const PATH2 = "/v1/users/profile:deleteImage"; // before `profile%3AdeleteImage`
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Describe the solution you'd like

Add a cli option (like `decodeSpecialCharacter`)

## Describe alternatives you've considered

Run GitHub action or pre-commit on my own.

## Additional context

file names and object properties are out of scope.

**Comment by solufa** [comment]
Thanks.
I'll implement this.

**Comment by solufa** [comment]
@matamatanot 

Please update.
Special characters are automatically decoded.
https://github.com/aspida/aspida/#define-endpoints-that-contain-special-characters

**Comment by matamatanot** [comment]
I personally feel that` decodeSpecialChars: true` can be default in v2(Breaking change).
I would like to hear other opinions.
