### ISSUE TITLE
How to handle error using `aspida-fetch` with `aspida-swr` and `aspida-react-query`

### ISSUE THREAD

**Issue by matamatanot** [aspida/aspida#613]
## Description

Default fetch API resolve any response code which is even 400 or 500.
So, `aspida-swr` and `aspida-react-query` return data not error.

How should I handle the error?

## Describe the solution you'd like

`aspida-fetch` accept a new option.

## Describe alternatives you've considered

Extend Fetch API(Keep typeof `fetch` interface) and pass is as first argument  of `aspida-fetch`.

## Additional context

It is a very short code, so it is easy to fork and handle by yourself.

https://github.com/aspida/aspida/blob/19d05280e59ad45ba638ee951ebf217f8085a1f4/packages/aspida-fetch/index.ts#L38-L45

```
if (400 <= res.status) {
  throw new Error(`${res.status}`);
}
```

**Comment by solufa** [comment]
@matamatanot 

Does this method solve the problem?

```ts
const { data } = useAspidaSWR(apiClient.hoge, 'get') // add 'get'
console.log(data?.status) // undefined -> 500
```

**Comment by matamatanot** [comment]
@solufa 
No.
React Query and swr should be able to recognize internally that the response is an error.

https://react-query.tanstack.com/guides/query-functions#handling-and-throwing-errors

> For React Query to determine a query has errored, the query function must throw. Any error that is thrown in the query function will be persisted on the error state of the query.

https://swr.vercel.app/docs/error-handling

> If an error is thrown inside fetcher, it will be returned as error by the hook.

**Comment by matamatanot** [comment]
It would be good if `aspida-fetch` could be configurable in the same way that `ky` treats non-2xx status codes as errors.
`aspida-swr` and `aspida-react-query` are not a problem here.

**Comment by solufa** [comment]
That sounds good to me.
I'll think of a way to implement it.

**Comment by solufa** [comment]
@matamatanot 

I added throwHttpErrors option.
Read the README for more details, including error handling.
https://github.com/aspida/aspida/tree/master/packages/aspida-fetch

Thanks for the very useful suggestions!
