### ISSUE TITLE
When no response data is available, `SyntaxError: Unexpected end of JSON input`

### ISSUE THREAD

**Issue by matamatanot** [aspida/aspida#628]
## Description

If the body of the response is empty (e.g. 204 No content), a parsing error will occur.

## Environment

- **Package version:**
  `v1.3.0`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `12`
- **npm version:**
  
  `6`

## Additional context

In some cases, such as the DELETE method, the response may be empty.
In this case, `res.json()` will fail.

**Before**
```
delete: (option: { headers: Methods1['delete']['reqHeaders'], config?: T }) =>
            fetch<Methods1['delete']['resBody'], BasicHeaders, Methods1['delete']['status']>(prefix, prefix1, DELETE, option).json(),
```

**After**
```
delete: (option: { headers: Methods1['delete']['reqHeaders'], config?: T }) =>
            fetch<Methods1['delete']['resBody'], BasicHeaders, Methods1['delete']['status']>(prefix, prefix1, DELETE, option)
```

**Comment by matamatanot** [comment]
I wrote the following, but I am not sure if it is correct.

```
delete: {
    resBody: unknown;
    status: number;
};
```

**Comment by solufa** [comment]
@matamatanot 

When you omit the `reqBody`, `res.json()` changes to `res.send()`, does this solve the problem?

```ts
delete: {
    status: number;
};
```

**Comment by matamatanot** [comment]
@solufa
That's fine for me.
