### ISSUE TITLE
Create get() only instead of get() and $get() both

### ISSUE THREAD

**Issue by matamatanot** [aspida/aspida#644]
## Description

Currently, there are plain `get()` and wrapper `$get()`.
Our team would like to use only `get()`, so we would like an option to not generate `$get()`.

## Describe the solution you'd like

Add a configurable option.

## Describe alternatives you've considered

Lint rule

**Comment by solufa** [comment]
I added outputMode option.
https://github.com/aspida/aspida#options-of-aspidaconfigjs
