### ISSUE TITLE
[useAspidaSWRV]コンポーネント外からフラグを渡されるコンポーネントにおいてenabledの変更が反映されない

### ISSUE THREAD

**Issue by TeXmeijin** [aspida/aspida#682]
## Description

**props経由でenabled判定に必要となるデータを渡されているコンポーネントが、useAspidaSWRVを利用していると、enabledが反転した後も描画結果が変わらない**

useAspidaSWRVがラップしているuseSWRVを直接使った場合はデータがロードされますので、useAspidaSWRV固有の問題です。

## Environment

以下再現リポジトリを参照。
https://github.com/TeXmeijin/use-aspida-swrv-reproduce

## Additional context

実装を拝見したところ、SWRVを使う場合は、Keyに対して関数を渡すことでenabledの変更を検知します。しかしuseAspidaSWRVのラップ処理ではkeyに文字列を必ず渡します。ここが違いのような気はします。

**Comment by TeXmeijin** [comment]
props更新時に再レンダリングされる

```
export default defineComponent({
  props: {
    planetData: {
      type: Object,
      required: true,
    },
  },
  setup(props) {
    const { data: planetsData3, error: planetsError3 } = useAspidaSWRV(
      client.planets._id(2),
      {
        enabled: !!props.planetData,
      }
    );

    return {
      planetsData3,
      planetsError3,
    };
  },
});
```

される

```
export default defineComponent({
  props: {
    planetData: {
      type: Object,
      required: true,
    },
  },
  setup(props) {
    const { data: planetsData3, error: planetsError3 } = useSWRV(
      () => !!props.planetData && client.planets._id(2).$path(),
      () => client.planets._id(2).$get()
    );

    return {
      planetsData3,
      planetsError3,
    };
  },
});
```

**Comment by TeXmeijin** [comment]
enabledを`Computed<boolean>`型にすると動作しました。

```
export default defineComponent({
  props: {
    planetData: {
      type: Object,
    },
  },
  setup(props) {
    const { data: planetsData3, error: planetsError3 } = useMyAspidaSWRV(
      client.planets._id(2),
      {
        enabled: computed(() => !!props.planetData),
      }
    );

    return {
      planetsData3,
      planetsError3,
    };
  },
});
```

以下たたきの実装
```
  const method = typeof key === "string" ? key : "$get";
  const opt = typeof key === "string" ? (option as any)[0] : key;

  const enabled =
    typeof opt?.enabled === "object" ? opt.enabled.value : ref(!opt?.enabled);

  return useSWRV(
    () => (enabled.value ? null : api.$path(opt)),
    () => api[method](opt),
    opt
  );
```

**Comment by TeXmeijin** [comment]
ComputedRefの場合は本当はユーザー定義型ガードを実装しないといけない気はする

**Comment by solufa** [comment]
@TeXmeijin 
これだとどうですかね？
https://github.com/TeXmeijin/use-aspida-swrv-reproduce/pull/1

**Comment by LumaKernel** [comment]
v1.7.1であってv1.8.0で `enabled` がなくなっていたので、なにかミスったかとおもったが、 https://github.com/aspida/aspida/commit/1056178da49845d9598392a4d7e1f60d9dfa7f77 で消えていた。
おそらく、この後に適切な修正を入れて、それでリリースということだったのだろうが、確認が漏れていた…。

他のパッケージも確認したがほかは特になし。

案は考えたが破壊はとりあえず無しにしたいため、v1.9.0 で修正とともに出す予定。

**Comment by LumaKernel** [comment]
useSWRVってvueの文脈ではある意味で不純です。
`{data}=useSWRV(key)`のkeyの更新が検知されることはないです。
`data` は `key` や useSWRVのオプションに依存していません(computedの関係にない)。

keyやオプションが変わりうる操作で自分自身が新しいものに変わるべきという知識を使用者が持っている必要があることになります。

よって、

- 唯一不純であることをゆるすエントリーポイント（ここではpages配下のvueファイル）でのみuseSWRV(useAspidaSWRVも含む)を使い、あとは単なるデータとして他のコンポーネントに配る。
- コンポーネント（たとえば `<fetch-data3/>`）が不純であるという知識を前提に、 `<fetch-data3 :planetData="planetsData" :key="planetsData"></fetch-data3>` などのように key を指定し、再生成(つまりsetupの再実行)を強制する。

という方法を取るのが正攻法ということになります。

これはReactでも同様です。

`enabled`の設計は（必要かはさておき）問題ない、という認識です。

（この結論に至るまでに結論が5転ぐらいしたので大変に難しいとは思います…）

**Comment by LumaKernel** [comment]
`enabled` ではなく `refreshInterval` というオプションで考えてみるとわかりやすいかもしれません。これも同様に、切り分けたコンポーネント内で prop に依存して変動させても反映されませんが、それが SWR の利点を享受するための設計上の制約 ということかと思います。（SWR cacheでリアクティビティの文脈とは一致しないステート制御をするが便利な機能を提供する）

**Comment by LumaKernel** [comment]
enabled 固有の問題なのではないか？と思っていた際の考察は、結局はこの issue とは関係ないとわかったので、 https://github.com/aspida/aspida/pull/726#issuecomment-1062685981 に書きました。

**Comment by LumaKernel** [comment]
もう正しそうな方法を一つ思いつきました。

まずトップレベルで

```ts
useAspidaSWRV(api....)
```

としておいて、

```ts
useSWRV("<useAspidaSWRVで使われたキー>")
```

とすることで、キャッシュから受け取るのみの状態になり、トップレベルでデータ管理しつつ、データ使用を下位コンポーネントでするという事もできますね。

`<useAspidaSWRVで使われたキー>` を使えるようにする feature はかなりありそうだ。
