### ISSUE TITLE
feature request: “exactOptionalPropertyTypes”: true へ対応し、Optionalな型に | undefined もつけること

### ISSUE THREAD

**Issue by kondei** [aspida/aspida#688]
## Description

TypeScript 4.4 から `exactOptionalPropertyTypes` というオプションが追加されています
これをtrueにするとaspidaのrequired: falseで生成された型が

```
a?: T
```

の形式であるためundefinedを受け付けず、今までペイロードに

```
{
  a: isB ? b : undefined
}
```

のように書けていたところがエラーになります
対応を希望します

## Describe the solution you'd like

Optionalな型定義ファイルを

```
a?: T | undefined
```

の形式で出力するようにする

## Describe alternatives you've considered
```
{
...(
  isA
  ? {
    a: b
  }
  : {}
)
}
```

と書くことで回避できますが冗長です

## Additional context
openapi2aspidaを使って生成したコードでこれが起きており、型定義ファイルを生成しているのはaspida側だと思われたのでここにissueを立てました
間違っているかもしれません

**Comment by LumaKernel** [comment]
Thank you.
Aspida と openapi2aspida 両方に変更が必要でした。
aspida 側の修正ができ、o2aが解決されないままこのissueはcloseされますが、すぐに o2a 側も修正します。

**Comment by kondei** [comment]
ありがとうございます
