### ISSUE TITLE
TypeScript type exports fail when type is imported from a module in vite or esbuild

### ISSUE THREAD

**Issue by keiya01** [aspida/aspida#697]
## Description

I'm using [vite](https://github.com/vitejs/vite). And when I import api from `$api.ts`, the following error is thrown.

```
The requested module '/path/to/api/index.ts' does not provide an export named 'Methods'
```

This issue is solved by [type import](https://github.com/vitejs/vite/issues/731#issuecomment-678625456).

Could you import `Methods` type with `type import` in generated `$api.ts`?

related issue: https://github.com/vitejs/vite/issues/731

## Environment

- **Package version:**
  
  `"@aspida/fetch": "^1.7.1"`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v17.3.1`
- **npm version:**
  
  `8.3.1`

**Comment by LumaKernel** [comment]
resolved by https://github.com/aspida/aspida/pull/712
v1.8.0 will be released soon. Thank you for your patience.
