### ISSUE TITLE
Provide .esm.js and .mjs files with @aspida/swr

### ISSUE THREAD

**Issue by ippeiukai** [aspida/aspida#737]
## Description

[SWR](https://github.com/vercel/swr/tree/1.2.2) provides esm and mjs bundling support.
https://github.com/vercel/swr/blob/f24c621ebb29d423aa15ecbab01d7316daa0a588/package.json#L17-L22

Because `@aspida/swr` does not provide mjs currently, having `import { SWRConfig } from 'swr';` in our codebase makes Next.js bundler to include both .mjs and .js versions of SWR library to be used by our own `import ... from swr` and aspida-swr's `require('swr')` respectively. This results in having two distinct `SWRConfigContext` contexts of SWR at runtime, and thus **configuration provided with `SWRConfig` component is ignored by the `useAspidaSWR` hook**.

（esmやmjsが有効なプロジェクトでは、直接の`import { SWRConfig } from 'swr';`と、ビルド時に`require('swr')`に変換された `@aspida/swr` 内からのimportが、それぞれ別のJSモジュールを読み込んでしまい、 `useAspidaSWR` が `SWRConfig` コンポーネントで指定した設定を無視する状態になります。SWRと同様にesmやmjsでのバンドリングもサポートしていただけると助かります。）

## Describe the solution you'd like

`@aspida/swr` to provide esm and mjs bundling support also.

## Describe alternatives you've considered

We have ended up maintaining a copy of `aspida/swr/index.ts` in our codebase for now.

**Comment by solufa** [comment]
v1.13.0で対応しました
