### ISSUE TITLE
Certain type checking of query, reqBody and resBody fails since v1.10.0

### ISSUE THREAD

**Issue by SegaraRai** [aspida/aspida#754]
## Description

Certain type checking no longer passes due to restrictions introduced in #750.
(tsc complains that `Index signature for type 'string' is missing in type ...`)
Repro: https://stackblitz.com/edit/aspida-bug-repro?file=README.md

## Environment

- **Package version:**
  
  `v1.10.0`
- **OS:**
  
  - [x] Linux
  - [x] Windows
  - [ ] macOS
- **Node.js version:**
  
  `16.14.2`
- **npm version:**
  
  `7.17.0`

## Additional context

Downgrading to v1.9.1 solves the issue.

**Comment by LumaKernel** [comment]
Thanks.
This PR https://github.com/aspida/aspida/pull/753 may fix this.
I'll release soon.

**Comment by SegaraRai** [comment]
Confirmed working with v1.10.1, thanks!
