### ISSUE TITLE
[question]form dataを指定した際のNode.jsでの挙動について

### ISSUE THREAD

**Issue by AkifumiSato** [aspida/aspida#763]
reqFormatでform dataを指定してかつ、node.jsでリクエストを実装する際の挙動についての質問です。
調べたところ以下のツイートを見つけました。
https://mobile.twitter.com/m_mitsuhide/status/1364227043848712202

reqFormatはbrowser fetchでのみ有効なのでしょうか？

**Comment by solufa** [comment]
グローバルにFormDataが存在する環境以外では使えません

node.jsのform-dataに対応する検討をしたこともありましたが実装が複雑になりすぎるため見送りました
https://www.npmjs.com/package/form-data
