### ISSUE TITLE
RESTクライアントがfetchの場合でもaxiosと同様にシリアライズ処理ができるようにしてほしい

### ISSUE THREAD

**Issue by moriyashiori** [aspida/aspida#775]
## Description

query parameterに配列が含まれる場合、queryのシリアライズが必要となります
READMEにてREST クライアント"axios"の場合の実装方法は用意されているのですが、
"fetch"ではコンフィグの形式が異なるためparamsSerializerが利用できません

## Describe the solution you'd like

aspida-"fetch"の場合でもシリアライズ処理をサポートしていただきたいです

**Comment by solufa** [comment]
機能要望ありがとうございます

資金はあるが採用活動の時間がなくOSSに割く人手が不足している状況です
aspidaエコシステムの製品ほとんどを私自身も利用しているのでメンテナンス自体が中止することはありませんが直近はバグやセキュリティパッチ対応で手一杯です

秋くらいからOSSのための採用を開始する見込みなのでもうしばらくお待ちください

**Comment by solufa** [comment]
上記PRのおかげで対応出来ました

v1.11.0リリース済みです

**Comment by moriyashiori** [comment]
ご対応いただきありがとうございました
