### ISSUE TITLE
Add peer dependencies

### ISSUE THREAD

**Issue by SegaraRai** [aspida/aspida#776]
## Description

pnpmのような依存関係を厳密に管理するパッケージマネージャでは直接依存関係にないパッケージが参照できない（`@aspida/axios`から`axios`が使えない）ことがあります
`peerDependencies`に`axios`を追加すると解消します

`@aspida/node-fetch`、`@aspida/react-query`、`@aspida/swr`、`@aspida/swrv`についてもおそらく同様です

## Environment

- **Package version:**
  
  `v1.10.3`
- **OS:**
  
  - [ ] Linux
  - [x] Windows
  - [ ] macOS
- **Node.js version:**
  
  `v16.15.1`
- **npm version:**
  
  `8.11.0`

## Additional context

Reproが必要な場合は用意します

**Comment by solufa** [comment]
v1.13.1で対応しました
