### ISSUE TITLE
Support axios@1.x

### ISSUE THREAD

**Issue by su8ru** [aspida/aspida#788]
## Description

axios 1.x 系で `@aspida/axios` を使用すると

```
throw new AxiosError('options must be an object', AxiosError.ERR_BAD_OPTION_VALUE);
```

のようなエラーが生じます。

Repro: https://stackblitz.com/edit/aspida-axios-1-x?file=index.ts&view=editor

## Describe alternatives you've considered

`peerDependencies` があれば warning が出てくれるのですが…（関連: #776）

## Additional context

詳細は追いきれていませんが、`paramsSerializer` の指定方法が変わっているようです。

- https://github.com/aspida/aspida/blob/main/packages/aspida-axios/src/index.ts#L26
- https://github.com/axios/axios/issues/5142#issuecomment-1280874080

**Comment by pipboy3000** [comment]
axios v1.3.5で`paramsSerializer`が関数を受け取るようになった( https://github.com/axios/axios/commit/a56c8661209d5ce5a645a05f294a0e08a6c1f6b3) ので、エラーは解消したと思います。

**Comment by solufa** [comment]
v1.13.0からaxios v1でテストを実施するようにしました
