### ISSUE TITLE
feature request: “exactOptionalPropertyTypes”: true 指定時に、AspidaParams の型エラー

### ISSUE THREAD

**Issue by nagasawaryoya** [aspida/aspida#794]
## Description

[exactOptionalPropertyTypes](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) を `true` にした際に、型エラーが発生します。
![スクリーンショット 2023-04-04 13 26 20](https://user-images.githubusercontent.com/53528726/229686894-e437d012-f5b7-4520-b6d3-0d383f641699.png)

### 案1
`AspidaParams` の `config?: Config` を `config?: Config | undefined` に変更
https://github.com/aspida/aspida/blob/dc884ffdeb4ac235290fe97b54aa7dc90a0287a9/packages/aspida/src/index.ts#L25-L30

### 案2
1. `createTemplate()` の `AspidaClient<T>` を `AspidaClient<T | undefined>` に変更
https://github.com/aspida/aspida/blob/dc884ffdeb4ac235290fe97b54aa7dc90a0287a9/packages/aspida/src/buildTemplate.ts#L44
2. `AspidaClient<AxiosRequestConfig>` を `AspidaClient<AxiosRequestConfig | undefined>`
https://github.com/aspida/aspida/blob/9ac427bf3cfd049908fa697148414d95873ebb5e/packages/aspida-axios/src/index.ts#L7
3. `AspidaParams<AxiosRequestConfig>` を `AspidaParams<AxiosRequestConfig | undefined>`
https://github.com/aspida/aspida/blob/9ac427bf3cfd049908fa697148414d95873ebb5e/packages/aspida-axios/src/index.ts#L13

## Describe alternatives you've considered

`aspida.config.js` で `input` オプションで指定したディレクトリに `exactOptionalPropertyTypes` を `false` にした tsconfig.json を生成していますが、他の方法があると嬉しいです。

## Additional context
こちらが関連の [issue](https://github.com/aspida/aspida/issues/688) です。
案2の場合 axios 以外にも修正が必要かもしれません。

また、別途解決方法がありましたらそちらをご教授いただきたいです。

**Comment by solufa** [comment]
@nagasawaryoya 
報告ありがとうございました。
aspida@1.12.0 で対応しました。

**Comment by nagasawaryoya** [comment]
@solufa 

ご対応いただきありがとうございます。
問題なく動作していることを確認できました。
