### ISSUE TITLE
[openapi2aspida] trailing slash is not added even though trailingSlash is set as true

### ISSUE THREAD

**Issue by takerfume** [aspida/aspida#796]
## Description

trailing slash is not added even though trailingSlash is set as true.

My aspida.config.js is the following.
```
// @ts-check

/** @type {Partial<import('aspida/dist/getConfigs').AspidaConfig>} */
const aspidaConfig = {
  input: 'src/api',
  trailingSlash: true,
}

module.exports = aspidaConfig
```

And I run the following command.
`rm -rf ./src/api && npx openapi2aspida -i http://localhost:8100/api/v1/public/openapi.json -o src/api`

However, trailing slash is not added to path in automatically generated code.

## Environment

- **Package version:**
  
openapi2aspida's version
  `v0.21.0`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v20.1.0`
- **npm version:**
  
  `9.6.4`

## Additional context

I also asked the same question in openapi2aspida repo ( https://github.com/aspida/openapi2aspida/issues/241 )

**Comment by solufa** [comment]
Fixed in openapi2aspida@0.23.1
