### ISSUE TITLE
A warning message appears that bin generation could not be performed during installation.

### ISSUE THREAD

**Issue by dadajam4** [aspida/aspida#802]
## Description

After upgrading `@aspida/fetch` from 1.12.0 to 1.13.1, the following warning appears during installation.

```
 WARN  Failed to create bin at /Users/dadajam4/projects/hr/ts-openapi-client/node_modules/.pnpm/@aspida+fetch@1.13.1/node_modules/@aspida/fetch/node_modules/.bin/fetch. The source file at /Users/dadajam4/projects/hr/ts-openapi-client/node_modules/.pnpm/@aspida+fetch@1.13.1/node_modules/@aspida/fetch/bin/index.js does not exist.
 WARN  Failed to create bin at /Users/dadajam4/projects/hr/ts-openapi-client/node_modules/.bin/fetch. The source file at /Users/dadajam4/projects/hr/ts-openapi-client/node_modules/@aspida/fetch/bin/index.js does not exist.
```

## Environment

- **Package version:**
  
  `v1.13.1`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v18.13.0`
- **npm version:**
  
  `8.19.3`

## Additional context

It is installed with pnpm. Version is 8.5.0.

I think `@aspida/fetch` is a package that does not need bin in the first place, so I am guessing that this is due to the fact that bin was appended to the unnecessary package.json in the following commit.

https://github.com/aspida/aspida/commit/b58dc3c25c427b16d95ac93856b1ee485e5386b4#diff-fc15df7f3ebb1259ef6ebadb84334214ab2e436e264eec7eb7a024aac376296b

**Comment by solufa** [comment]
fixed in v1.13.2
